"use strict";

var resources = {
  ke: {
    label: "Kindergartner — Years 1 and 2 (Ages 5–7)",
    cards: [
      { type: "Phonics and reading books", title: "Early reader library", items: ["Bob Books Sets 1–4 — phonics based, starts at letter sounds", "Elephant and Piggie series — Mo Willems (dialogue, humour, vocabulary)", "Fly Guy series — Tedd Arnold (non-fiction hybrid, great vocabulary)", "Pete the Cat series — James Dean", "Biscuit series — Alyssa Capucilli (companion, routine)", "Starfall decodable books (free PDF downloads at starfall.com)", "Dragon Loves Tacos — Adam Rubin (vocabulary, inference)", "Rosie Revere Engineer — Andrea Beaty (growth mindset)", "Ada Twist Scientist — Andrea Beaty (curiosity and science)", "Henry and Mudge series — Cynthia Rylant (friendship, simple chapters)"] },
      { type: "Ontario curriculum reference", title: "Grade 1–2 official curriculum and EFI support", items: ["Ontario Mathematics Curriculum (2020) — dcp.edu.gov.on.ca, the official Number/Algebra/Data/Spatial Sense/Financial Literacy expectations by grade", "Ontario Language Curriculum (2023) — official 4-strand structure (Foundations, Comprehension, Composition, Transferable Skills)", "OCDSB French Immersion program page — ocdsb.ca, confirms EFI structure (Math/English Language in English; other subjects in French at 60%)", "IXL Ontario Grade 1/2 — ca.ixl.com/standards/ontario, free practice mapped directly to specific Ontario expectations", "Ontario curriculum unpacked by strand (free teacher resources) — ontariomath.support, lesson-level detail on each expectation", "TVO Learn — free, Ontario-curriculum-aligned practice and videos for math and literacy", "Je Lis, Tu Lis (French levelled readers) — ask the school librarian for EFI-appropriate French reading support", "Mathies.ca — free Ontario Ministry-funded math learning tool aligned to the curriculum"] },
      { type: "Read-aloud chapter books", title: "Parent read-aloud picks — Years 1 and 2", items: ["Charlotte's Web — E.B. White (friendship, life, death — rich vocabulary)", "Stuart Little — E.B. White (adventure, ingenuity)", "My Father's Dragon — Ruth Stiles Gannett (problem solving, vivid imagination)", "The Boxcar Children — Gertrude Warner (independence, resourcefulness)", "Winnie the Pooh — A.A. Milne (language play, friendship, philosophy)", "The Cricket in Times Square — George Selden (city, music, friendship)", "James and the Giant Peach — Roald Dahl (imagination, courage)", "The BFG — Roald Dahl (invented words, rich vocabulary)", "The Wind in the Willows — Kenneth Grahame (classic language)", "Pippi Longstocking — Astrid Lindgren (independence, imagination)"] },
      { type: "Math tools and games", title: "Hands-on math resources", items: ["Zingo Number Bingo — Educational Insights", "Sum Swamp board game — Learning Resources", "Khan Academy Kids app — free, adaptive, grade 1 math track", "Prodigy Math Game — free, curriculum-aligned, game-based", "Mathlink cubes — for counting, patterns, basic algebra thinking", "Base-10 blocks — for place value understanding", "Osmo Numbers — iPad-based, physical tiles with digital game", "Sleeping Queens card game — memory and addition", "Blokus — spatial reasoning (all ages)", "Times Tales — story-based multiplication memory (Year 2 intro)"] },
      { type: "Science kits and tools", title: "Hands-on science for ages 5–7", items: ["Thames and Kosmos Kids First Science Lab Kit — 20 safe beginner experiments", "National Geographic Mega Fossil Dig Kit — geology and paleontology", "Steve Spangler Science Experiments on YouTube — free, incredible", "Grow Crystal Kit — chemistry basics", "Backyard Birds of Eastern Ontario — field guide (Ottawa specific)", "Magnifying glass and bug catcher kit — Melissa and Doug", "Mini microscope — Carson MicroBrite Plus", "Nature Anatomy — Julia Rothman (illustrated nature reference)", "The Big Book of Science Experiments — DK", "iNaturalist app — citizen science, identify plants and animals"] },
      { type: "Apps and digital tools", title: "Screen time that builds skills", items: ["Khan Academy Kids — reading and math (free)", "Duolingo ABC — literacy and letter sounds (free)", "Starfall.com — phonics (free)", "Epic! Books for Kids — library subscription", "Prodigy Math — game-based curriculum math (free)", "Scratch Jr — iPad coding introduction (free)", "YouTube: Crash Course Kids — science concepts", "YouTube: SciShow Kids — natural world curiosity", "PBS Kids games — curriculum-aligned (free)", "CBC Kids — Canadian content, age-appropriate news"] },
      { type: "Ottawa resources", title: "Local enrichment for Kindergartner", items: ["Ottawa Public Library — all branches, free library card gives Epic! Books access", "Canadian Museum of Nature — free Sunday mornings first of each month", "Canada Science and Technology Museum — hands-on, excellent for this age", "Canadian Museum of History (Gatineau) — free on Canada Day and special days", "Ottawa Children's Festival — annual, May (book tickets early)", "Rideau Canal Skateway — world's longest naturally refrigerated rink, January–February", "Gatineau Park trails — free year-round, 165 km of paths", "NCC family cycling days — car-free Sundays, Colonel By Drive", "Sportball Ottawa — multi-sport program ages 2–8", "Ottawa Carleton District School Board French immersion — apply in Kindergarten"] }
    ]
  },
  km: {
    label: "Kindergartner — Years 3–5 (Ages 7–10)",
    cards: [
      { type: "Chapter books Years 3–4", title: "Grade 3–5 reading level", items: ["The Lion the Witch and the Wardrobe — C.S. Lewis", "Matilda — Roald Dahl", "Holes — Louis Sachar (Newbery Medal)", "Because of Winn-Dixie — Kate DiCamillo", "The One and Only Ivan — Katherine Applegate", "Hatchet — Gary Paulsen", "Number the Stars — Lois Lowry", "Bridge to Terabithia — Katherine Paterson", "Tuck Everlasting — Natalie Babbitt", "Esperanza Rising — Pam Munoz Ryan"] },
      { type: "Ontario curriculum reference", title: "Grade 3–5 official curriculum, EQAO, and EFI support", items: ["EQAO Grade 3 official sample tests — eqao.com, the real format used in the actual assessment", "Ontario Mathematics Curriculum (2020) Grade 3–5 — dcp.edu.gov.on.ca, especially Strand B (Number) for multiplication-fact timing", "IXL Ontario Grade 3/4/5 — ca.ixl.com/standards/ontario, practice mapped to specific expectations", "TVO Learn — free Ontario-aligned math and literacy practice", "Mathies.ca — free Ontario Ministry math tool, includes manipulatives and games tied to the curriculum", "OCDSB EFI transition information (Grade 4+) — ocdsb.ca, confirms 60% French continues through Grade 6", "Je Lis, Tu Lis and Boukili (free French levelled reading platform) — for EFI reading support at home"] },
      { type: "Chapter books Year 5", title: "Grade 5–6 reading level", items: ["The Phantom Tollbooth — Norton Juster", "Anne of Green Gables — L.M. Montgomery (Canadian classic)", "The Outsiders — S.E. Hinton", "Animal Farm — George Orwell (read and discuss together)", "I Am Malala — young readers edition", "A Long Walk to Water — Linda Sue Park", "The Watsons Go to Birmingham — Christopher Paul Curtis", "Inside Out and Back Again — Thanhha Lai", "Ender's Game — Orson Scott Card", "The Secret Garden — Frances Hodgson Burnett"] },
      { type: "Math enrichment Years 3–5", title: "Acceleration resources", items: ["Beast Academy 3A–5D — Art of Problem Solving (visual, challenging, excellent)", "Math Kangaroo past papers — free at mathkangaroo.ca", "Singapore Math Challenging Word Problems Grade 3–5", "Murderous Maths full series — Kjartan Poskitt", "Khan Academy Grade 4–6 (free, mastery-based)", "AMC 8 past papers 2010–2023 — free at artofproblemsolving.com", "Brilliant.org Level 1 Foundation", "The Number Devil — Hans Magnus Enzensberger", "Zaccaro Primary Challenge Math", "University of Waterloo GAUSS contest past papers — free online"] },
      { type: "Coding pathway", title: "From Scratch to Python", items: ["Scratch.mit.edu — free, browser-based", "Code.org Grade 4–6 courses — free", "Tynker Junior and Intermediate — gamified curriculum", "Python for Kids — Jason Briggs (excellent first Python book)", "Hello Ruby: Adventures in Coding — Linda Liukas", "Kano Computer Kit — build a computer and code it", "CS First by Google — free club curriculum, 9 themes", "Sphero BOLT — code a robot with blocks or JavaScript", "App Lab on Code.org — text-based JavaScript, free", "Replit.com — free browser Python, no installation needed"] },
      { type: "Competition preparation", title: "Ottawa competition calendar", items: ["Math Kangaroo Canada — March annually — register by February", "AMC 8 — November annually — school registers", "University of Waterloo GAUSS contest — Grade 7 and 8, May", "Ottawa Regional Science Fair — March/April", "Norman Bethune Essay Contest — Ontario schools, check annually", "Scholastic Art and Writing Awards Canada — January deadline", "Spelling Bee Canada — school level first", "Geography Bee Canada — National Geographic Canada", "UOttawa math outreach programs — check math.uottawa.ca", "Canadian Mathematical Society competitions — cms.math.ca"] },
      { type: "Music and arts", title: "RCM pathway and arts resources", items: ["Royal Conservatory of Music — find certified Ottawa teachers", "RCM Theory Workbooks Grade 1–5", "Piano Adventures series Primer through Level 5", "Essential Elements for Strings — violin and cello beginner method", "Note Rush app — note reading flashcards, gamified", "Teoria.com — free ear training and music theory exercises", "Pro Metronome app — free, excellent for practice discipline", "Ottawa Youth Orchestra — junior program, audition in spring", "RCM Celebrations Series — excellent graded recital repertoire", "YouTube: TwoSet Violin — classical music made compelling for youth"] }
    ]
  },
  ge: {
    label: "Grade 3 Student — Years 1 and 2 (Ages 8–10)",
    cards: [
      { type: "Reading list Years 1–2", title: "Grade 5–7 level novels", items: ["The Lightning Thief — Rick Riordan", "Wonder — R.J. Palacio", "Hatchet — Gary Paulsen", "Holes — Louis Sachar", "The Giver — Lois Lowry", "A Wrinkle in Time — Madeleine L'Engle", "Number the Stars — Lois Lowry", "Refugee — Alan Gratz", "Brown Girl Dreaming — Jacqueline Woodson", "Hidden Figures Young Readers — Margot Lee Shetterly"] },
      { type: "Ontario curriculum reference", title: "Grade 3–4 official curriculum, EQAO, and EFI support", items: ["EQAO Grade 3 official sample tests — eqao.com, the actual format and digital tools used in the assessment", "Ontario Mathematics Curriculum (2020) Grade 3–4 — dcp.edu.gov.on.ca, Strand B for multiplication-fact progression (×2/×5/×10 in Gr.3, full tables in Gr.4)", "IXL Ontario Grade 3/4 — ca.ixl.com/standards/ontario", "TVO Learn — free Ontario-aligned practice", "Mathies.ca — free Ontario Ministry math tool", "OCDSB French Immersion continuation info — ocdsb.ca, confirms 60% French through Grade 6", "Boukili — free French levelled reading platform for EFI support"] },
      { type: "Non-fiction Years 1–2", title: "Ideas and information books", items: ["Bomb — Steve Sheinkin", "The Boy Who Harnessed the Wind — William Kamkwamba", "A Short History of Nearly Everything young readers — Bill Bryson", "I Am Malala — Yousafzai (full text)", "The Code Book for Young Readers — Simon Singh", "Team Moon — Catherine Thimmesh", "Malala's Magic Pencil — Yousafzai", "DK Eyewitness Science full series", "The Disappearing Spoon young readers — Sam Kean", "National Geographic Kids World Atlas"] },
      { type: "Math acceleration Years 1–2", title: "From Grade 4 to pre-algebra", items: ["Beast Academy 4A–5D — Art of Problem Solving", "AMC 8 past papers 2010–2023 — free at artofproblemsolving.com", "Math Kangaroo past papers — free at mathkangaroo.ca", "Singapore Math Challenging Word Problems Grade 4–5", "Khan Academy Grade 5–6 full track — free", "Brilliant.org Foundation and Level 1", "Competition Math for Middle School — Jason Batterson", "Murderous Maths complete series — Kjartan Poskitt", "University of Waterloo GAUSS contest prep — free online", "Alcumus on artofproblemsolving.com — free adaptive problem sets"] },
      { type: "Writing resources Years 1–2", title: "From paragraph to research paper", items: ["Write Source Grade 5–6 — Houghton Mifflin", "Young Writers Project — youngwritersproject.org — free, publish online", "Scholastic Art and Writing Awards Canada — January deadline", "Daily 6-Trait Writing Grade 5–6 — Evan-Moor", "Grammar Girl Quick and Dirty Tips", "Purdue OWL Online Writing Lab — free MLA and citation guides", "Ottawa Public Library database access — free with library card", "The Canadian Encyclopedia — thecanadianencyclopedia.ca", "They Say I Say intro chapters — Gerald Graff", "Google Scholar — teach how to find and evaluate sources"] },
      { type: "Coding Years 1–2", title: "From Scratch to Python to Arduino", items: ["Python for Kids — Jason Briggs", "Code.org Grade 6–8 track — free", "Trinket.io — free browser Python, no installation", "CS Unplugged — csunplugged.org — free", "Automate the Boring Stuff with Python — Al Sweigart (free online)", "MIT App Inventor — build Android apps, free", "Arduino Starter Kit Official — excellent documentation", "Tinkercad — free 3D design and circuit simulation", "Raspberry Pi foundation projects — free guides", "CodingBat.com — free Python and Java practice problems"] },
      { type: "Ottawa programs", title: "Local enrichment for Grade 3 Years 1–2", items: ["Ottawa Carleton District Science Fair — register through school", "University of Ottawa Math outreach — math.uottawa.ca/youth", "Carleton University STEM programs — carleton.ca/science", "Ottawa Chess Club junior program — ottawachess.ca", "Code Kids Ottawa — summer and after-school coding camps", "Ottawa Robotics Tournament — FIRST LEGO League", "Ottawa Drama League youth programs", "Ottawa Youth Orchestra — auditions in spring", "Historica Canada Citizenship Challenge — historica.ca (free)", "Let's Talk Science Ottawa — Ottawa outreach programs"] }
    ]
  },
  gm: {
    label: "Grade 3 Student — Years 3–5 (Ages 10–13)",
    cards: [
      { type: "Literature Years 3–5", title: "Grade 8 to pre-university reads", items: ["To Kill a Mockingbird — Harper Lee", "1984 — George Orwell", "Lord of the Flies — William Golding", "The Great Gatsby — Fitzgerald", "Romeo and Juliet — Shakespeare (graphic novel then full text)", "Hamlet — Shakespeare", "Night — Elie Wiesel", "Animal Farm — Orwell", "Between the World and Me — Ta-Nehisi Coates", "Just Mercy — Bryan Stevenson young readers"] },
      { type: "Ontario curriculum reference", title: "Grade 5–7 official curriculum, EQAO Grade 6, and EFI transition", items: ["EQAO Grade 6 official sample tests — eqao.com, broader and longer than Grade 3's, covers all six math strands", "Ontario Mathematics Curriculum (2020) Grade 5–7 — dcp.edu.gov.on.ca, especially integers (new in Gr.6) and rational numbers (Gr.7)", "Ontario Mathematics Grades 7–8–9 Alignment Chart — shows exactly how Grade 7/8 content connects to Grade 9 academic math", "IXL Ontario Grade 5/6/7 — ca.ixl.com/standards/ontario", "CEMC Grade 7/8 open courseware — courseware.cemc.uwaterloo.ca, free University of Waterloo math enrichment aligned to Canadian curricula", "OCDSB Intermediate French Immersion info — ocdsb.ca, confirms French drops to 50% in Grade 7", "Information on Ontario's Grade 9 de-streamed math course — a 2021 policy change worth understanding ahead of high school planning"] },
      { type: "Big ideas non-fiction", title: "University-adjacent non-fiction", items: ["Sapiens Part 1 — Yuval Noah Harari", "A Brief History of Time Chapters 1–3 — Stephen Hawking", "Thinking Fast and Slow Introduction — Daniel Kahneman", "The Selfish Gene Chapters 1–2 — Richard Dawkins", "The Elegant Universe Chapters 1–2 — Brian Greene", "Godel Escher Bach Chapters 1–3 — Douglas Hofstadter", "Range — David Epstein", "Atomic Habits — James Clear", "The Code Breaker — Walter Isaacson", "The Structure of Scientific Revolutions excerpts — Thomas Kuhn"] },
      { type: "Math Years 3–5", title: "Algebra through pre-calculus", items: ["Art of Problem Solving Introduction to Algebra — Rusczyk", "Art of Problem Solving Precalculus — Rusczyk (Year 5)", "Art of Problem Solving Introduction to Geometry — Rusczyk (Year 4)", "AMC 8 past papers complete set — free", "AMC 10 past papers — begin Year 4", "University of Waterloo CAYLEY and FERMAT contests", "Brilliant.org Level 2–4", "Alcumus on AoPS — free adaptive problem sets, year-round", "3Blue1Brown YouTube — Essence of Calculus series", "Paul's Online Math Notes — free"] },
      { type: "Competition calendar Years 3–5", title: "What to enter and when to register", items: ["AMC 8 — November every year — register through school by October", "AMC 10 — November, Year 4 onwards", "Math Kangaroo Canada — March — register by February", "GAUSS contest Univ. of Waterloo — May", "Ottawa Regional Science Fair — March/April", "Canada-Wide Science Fair — May", "Sanofi Biogenius Canada — biotechnology focus, Year 5 target", "Scholastic Writing Awards Canada — January deadline", "Governor General's Academic Medal — awarded by school at graduation", "UOttawa Model UN Conference — check uottawa.ca annually"] },
      { type: "Leadership and service", title: "Ottawa opportunities", items: ["Ottawa Food Bank volunteer program — ottawafoodbank.ca", "CHEO Foundation events — youth fundraising and events", "Community Harvest Ottawa — food rescue", "Mayor's Youth Advisory Committee Ottawa — apply annually", "Ottawa Youth Council — ages 13–18, Year 5 onward", "Scouts Canada Ottawa — leadership built into program", "Historica Canada Heritage Fairs — research and presentation", "Youth Fusion Canada — school entrepreneurship programs", "Jack.org mental health youth leadership — ages 12+", "Students on Ice — polar expedition scholarship, apply age 14+"] },
      { type: "High school planning", title: "Ottawa IB and AP programs", items: ["Colonel By Secondary School — IB diploma programme", "Nepean High School — AP program", "Bell High School — AP and enriched science", "Lisgar Collegiate — top academic tradition, apply in Grade 8", "Gloucester High School — IB program, East Ottawa", "Ecole secondaire publique De La Salle — IB in French", "Johns Hopkins CTY summer — apply Grade 7 or 8", "UWaterloo Enrichment Centre — summer math and science", "UOttawa summer programs — check uottawa.ca/STEM", "Pre-college summer programs at various universities — apply Grade 9 onwards if a specific path of interest emerges"] }
    ]
  }
};
